# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  
  # Use the full MarkdownView library
  pod 'MarkdownView'
  
  # Or use specific subspecs if you only need certain functionality:
  # pod 'MarkdownView/Core'
  # pod 'MarkdownView/MarkdownView'
  # pod 'MarkdownView/MarkdownParser'
  # pod 'MarkdownView/Litext'

end
